$(document).ready(function(){function i(b,c){$.ajax({url:"parser_class.py",type:"POST",data:{artist:b.data.name,limit:10},success:function(f){for(var f=jQuery.parseJSON(f),a=0;a<f.nodes.length;a++)c.addNode(f.nodes[a].name,{name:f.nodes[a].name,weight:f.nodes[a].rating,url:f.nodes[a].url}),0<a&&c.addEdge(b.name,f.nodes[a].name)},error:function(){console.log("oops")}})}function k(b){for(var c=$("input#name").val().split(" by "),f=0;f<c.length;f++)c[f]=toTitleCase(c[f]);var f=getApiKey(),a=c[0].replace(" ",
"+"),l=c[1].replace(" ","+"),b=getRequestUrl("track.getsimilar")+"&artist="+l+"&track="+a+"&api_key="+f+"&limit="+b+"&format=json";$.ajax({type:"GET",url:b,success:function(a){var a=a.similartracks.track,b=function(a){var a=$(a).get(0),d=a.getContext("2d"),b,g={init:function(d){b=d;b.screenSize(a.width,a.height);b.screenPadding(80);g.initMouseHandling()},redraw:function(){d.fillStyle="white";d.fillRect(0,0,a.width,a.height);b.eachEdge(function(a,b,g){d.strokeStyle="rgba(0,0,0, .333)";d.lineWidth=
1;d.beginPath();d.moveTo(b.x,b.y);d.lineTo(g.x,g.y);d.stroke()});b.eachNode(function(a,b){d.fillStyle="#2E4F4F";d.beginPath();d.arc(b.x,b.y,Math.sqrt(10*a.data.weight),0,2*Math.PI,!0);d.closePath();d.fill();d.fillStyle="#000";d.font="14pt Calibri";d.fillText(a.data.name,b.x-Math.sqrt(10*a.data.name.length),b.y+a.data.weight/4+25);d.fillText(a.data.artist,b.x-Math.sqrt(10*a.data.artist.length),b.y-a.data.weight/4-10)})},initMouseHandling:function(){var g,d,c,h=null;g=function(){h.node&&!0==h.node.fixed&&
i(h.node,b)};d=function(d){var g=$(a).offset(),d=arbor.Point(d.pageX-g.left,d.pageY-g.top);h&&null!==h.node&&(d=b.fromScreen(d),h.node.p=d);return!1};c=function(){clearTimeout(timeoutId);if(!(null===h||void 0===h.node))return null!==h.node&&(h.node.fixed=!1),h.node.tempMass=1E3,h=null,$(a).unbind("mousemove",d),$(window).unbind("mouseup",c),_mouseP=null,!1};$(a).mousedown(function(f){var e=$(a).offset();_mouseP=arbor.Point(f.pageX-e.left,f.pageY-e.top);if((h=b.nearest(_mouseP))&&null!==h.node)h.node.fixed=
!0;timeoutId=setTimeout(g,1E3);$(a).bind("mousemove",d);$(window).bind("mouseup",c);return!1});$(a).dblclick(function(d){var g=$(a).offset();_mouseP=arbor.Point(d.pageX-g.left,d.pageY-g.top);dblclicked=b.nearest(_mouseP);window.open("http://"+dblclicked.node.data.url,"_newtab")})}};return g};"object"===typeof e?e.eachNode(function(a){e.pruneNode(a)}):(e=arbor.ParticleSystem(1E3,600,0.5),e.parameters({gravity:!0,precision:0.9,dt:0.015}),e.renderer=b("#viewport"));$("#viewport").get(0).getContext("2d");
for(var b=e.addNode(c[0],{name:c[0],artist:c[1],weight:100,url:"http://www.google.com"}),g=0;g<a.length;g++)theWeight=100*parseFloat(a[g].match),e.addNode(a[g].name,{name:a[g].name,artist:a[g].artist.name,weight:theWeight,url:a.url}),e.addEdge(b,a[g].name);$("#container").fadeIn(1E3,"easeInQuad")},error:function(a,b){console.log(b)}})}function m(b){var c=$("input#name").val().split(":"),c=c[1].replace(" ",""),f=getApiKey();console.log(f);$.ajax({url:getRequestUrl("tag.gettopartist")+"&tag="+c+"&api_key="+
f+"&limit="+b+"&format=json",type:"GET",success:function(a){console.log(a)}})}$("#advanced_search").click(function(){$("#adv_search_opts").slideToggle(400,"easeOutCubic")});$("#about_link").click(function(){$("#about").slideToggle()});var e;$("input").keypress(function(b){if(13==b.which){b.preventDefault();$("container").fadeOut(100);var c=/^\d+$/,b=$("input#limit").val();if(!(0<b.length&&!1==c.test(b))&&!(20<b)){if(0==b||0==b.length)b=10;$("#adv_search_opts").is(":visible")&&$("#adv_search_opts").slideToggle();
var c=$("input#name").val(),f=/genre:\s*[A-z0-9]+(\s[A-z0-9&]*)*/;if(!0==/(([A-z0-9]+)\s*)+by\s([A-z0-9]+\s*)+/.test(c))console.log("track search"),k(b);else if(f.test(c))console.log("genre search"),m(b);else return $.ajax({url:"parser_class.py",type:"POST",data:{artist:$("input#name").val(),limit:b},success:function(a){var b=function(a){var a=$(a).get(0),b=a.getContext("2d"),d,c={init:function(b){d=b;d.screenSize(a.width,a.height);d.screenPadding(80);c.initMouseHandling()},redraw:function(){b.fillStyle=
"white";b.fillRect(0,0,a.width,a.height);d.eachEdge(function(a,d,c){b.strokeStyle="rgba(0,0,0, .333)";b.lineWidth=1;b.beginPath();b.moveTo(d.x,d.y);b.lineTo(c.x,c.y);b.stroke()});d.eachNode(function(a,d){b.fillStyle="#2E4F4F";b.beginPath();b.arc(d.x,d.y,Math.sqrt(10*a.data.weight),0,2*Math.PI,!0);b.closePath();b.fill();b.fillStyle="#000";b.font="14pt Calibri";b.fillText(a.data.name,d.x-4.12*a.data.name.length,d.y+Math.sqrt(10*a.data.weight)+20)})},initMouseHandling:function(){var b,c,f,e=null;b=function(){e.node&&
!0==e.node.fixed&&i(e.node,d)};c=function(b){var c=$(a).offset(),b=arbor.Point(b.pageX-c.left,b.pageY-c.top);e&&null!==e.node&&(b=d.fromScreen(b),e.node.p=b);return!1};f=function(){clearTimeout(timeoutId);if(!(null===e||void 0===e.node))return null!==e.node&&(e.node.fixed=!1),e.node.tempMass=1E3,e=null,$(a).unbind("mousemove",c),$(window).unbind("mouseup",f),_mouseP=null,!1};$(a).mousedown(function(h){var j=$(a).offset();_mouseP=arbor.Point(h.pageX-j.left,h.pageY-j.top);if((e=d.nearest(_mouseP))&&
null!==e.node)e.node.fixed=!0;timeoutId=setTimeout(b,1E3);$(a).bind("mousemove",c);$(window).bind("mouseup",f);return!1});$(a).dblclick(function(b){var c=$(a).offset();_mouseP=arbor.Point(b.pageX-c.left,b.pageY-c.top);dblclicked=d.nearest(_mouseP);window.open("http://"+dblclicked.node.data.url,"_newtab")})}};return c};"object"===typeof e?e.eachNode(function(a){e.pruneNode(a)}):(e=arbor.ParticleSystem(1E3,600,0.5),e.parameters({gravity:!0,precision:0.9,dt:0.015}),e.renderer=b("#viewport"));var c=jQuery.parseJSON(a);
$("#viewport").get(0).getContext("2d");for(a=0;a<c.nodes.length;a++)e.addNode(c.nodes[a].name,{name:c.nodes[a].name,weight:c.nodes[a].rating,url:c.nodes[a].url}),0<a&&e.addEdge(c.nodes[0].name,c.nodes[a].name);var f=0;e.eachNode(function(){console.log(c.nodes[f]);f++});$("#container").fadeIn(1E3,"easeInQuad")},error:function(a,b,c){console.log(c)}}),!1}}})});